# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bc3d772e5bd60c2e8ae4b174f954e21bcdb97ab9a985ed1b59e345c79bfd9886fccdd36bd7ca50d5e63cfcdf4fb53c821087ec05385d0d0366f18ff92ce18d2

test:
  secret_key_base: db167d7eea2457f72682941bbebfc4bd82668810db5b2cc1597297d131cdcddadce4e3be3449f74a242e55964c9b654d1920bea84b73ff760c97eeb055d810ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
